// Generated by gencpp from file xf_mic_asr_offline/GetOfflineResult.msg
// DO NOT EDIT!


#ifndef XF_MIC_ASR_OFFLINE_MESSAGE_GETOFFLINERESULT_H
#define XF_MIC_ASR_OFFLINE_MESSAGE_GETOFFLINERESULT_H

#include <ros/service_traits.h>


#include <xf_mic_asr_offline/GetOfflineResultRequest.h>
#include <xf_mic_asr_offline/GetOfflineResultResponse.h>


namespace xf_mic_asr_offline
{

struct GetOfflineResult
{

typedef GetOfflineResultRequest Request;
typedef GetOfflineResultResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetOfflineResult
} // namespace xf_mic_asr_offline


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xf_mic_asr_offline::GetOfflineResult > {
  static const char* value()
  {
    return "28bc8539466b604fc9101f0b3a34c375";
  }

  static const char* value(const ::xf_mic_asr_offline::GetOfflineResult&) { return value(); }
};

template<>
struct DataType< ::xf_mic_asr_offline::GetOfflineResult > {
  static const char* value()
  {
    return "xf_mic_asr_offline/GetOfflineResult";
  }

  static const char* value(const ::xf_mic_asr_offline::GetOfflineResult&) { return value(); }
};


// service_traits::MD5Sum< ::xf_mic_asr_offline::GetOfflineResultRequest> should match
// service_traits::MD5Sum< ::xf_mic_asr_offline::GetOfflineResult >
template<>
struct MD5Sum< ::xf_mic_asr_offline::GetOfflineResultRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_asr_offline::GetOfflineResult >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::GetOfflineResultRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_asr_offline::GetOfflineResultRequest> should match
// service_traits::DataType< ::xf_mic_asr_offline::GetOfflineResult >
template<>
struct DataType< ::xf_mic_asr_offline::GetOfflineResultRequest>
{
  static const char* value()
  {
    return DataType< ::xf_mic_asr_offline::GetOfflineResult >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::GetOfflineResultRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xf_mic_asr_offline::GetOfflineResultResponse> should match
// service_traits::MD5Sum< ::xf_mic_asr_offline::GetOfflineResult >
template<>
struct MD5Sum< ::xf_mic_asr_offline::GetOfflineResultResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_asr_offline::GetOfflineResult >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::GetOfflineResultResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_asr_offline::GetOfflineResultResponse> should match
// service_traits::DataType< ::xf_mic_asr_offline::GetOfflineResult >
template<>
struct DataType< ::xf_mic_asr_offline::GetOfflineResultResponse>
{
  static const char* value()
  {
    return DataType< ::xf_mic_asr_offline::GetOfflineResult >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::GetOfflineResultResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XF_MIC_ASR_OFFLINE_MESSAGE_GETOFFLINERESULT_H
