// Generated by gencpp from file xf_mic_asr_offline/SetString.msg
// DO NOT EDIT!


#ifndef XF_MIC_ASR_OFFLINE_MESSAGE_SETSTRING_H
#define XF_MIC_ASR_OFFLINE_MESSAGE_SETSTRING_H

#include <ros/service_traits.h>


#include <xf_mic_asr_offline/SetStringRequest.h>
#include <xf_mic_asr_offline/SetStringResponse.h>


namespace xf_mic_asr_offline
{

struct SetString
{

typedef SetStringRequest Request;
typedef SetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetString
} // namespace xf_mic_asr_offline


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xf_mic_asr_offline::SetString > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::xf_mic_asr_offline::SetString&) { return value(); }
};

template<>
struct DataType< ::xf_mic_asr_offline::SetString > {
  static const char* value()
  {
    return "xf_mic_asr_offline/SetString";
  }

  static const char* value(const ::xf_mic_asr_offline::SetString&) { return value(); }
};


// service_traits::MD5Sum< ::xf_mic_asr_offline::SetStringRequest> should match
// service_traits::MD5Sum< ::xf_mic_asr_offline::SetString >
template<>
struct MD5Sum< ::xf_mic_asr_offline::SetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_asr_offline::SetString >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_asr_offline::SetStringRequest> should match
// service_traits::DataType< ::xf_mic_asr_offline::SetString >
template<>
struct DataType< ::xf_mic_asr_offline::SetStringRequest>
{
  static const char* value()
  {
    return DataType< ::xf_mic_asr_offline::SetString >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xf_mic_asr_offline::SetStringResponse> should match
// service_traits::MD5Sum< ::xf_mic_asr_offline::SetString >
template<>
struct MD5Sum< ::xf_mic_asr_offline::SetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_asr_offline::SetString >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::SetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_asr_offline::SetStringResponse> should match
// service_traits::DataType< ::xf_mic_asr_offline::SetString >
template<>
struct DataType< ::xf_mic_asr_offline::SetStringResponse>
{
  static const char* value()
  {
    return DataType< ::xf_mic_asr_offline::SetString >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::SetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XF_MIC_ASR_OFFLINE_MESSAGE_SETSTRING_H
