// Generated by gencpp from file xf_mic_asr_offline/GetOfflineResultRequest.msg
// DO NOT EDIT!


#ifndef XF_MIC_ASR_OFFLINE_MESSAGE_GETOFFLINERESULTREQUEST_H
#define XF_MIC_ASR_OFFLINE_MESSAGE_GETOFFLINERESULTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xf_mic_asr_offline
{
template <class ContainerAllocator>
struct GetOfflineResultRequest_
{
  typedef GetOfflineResultRequest_<ContainerAllocator> Type;

  GetOfflineResultRequest_()
    : offline_recognise_start(0)
    , confidence_threshold(0)
    , time_per_order(0)  {
    }
  GetOfflineResultRequest_(const ContainerAllocator& _alloc)
    : offline_recognise_start(0)
    , confidence_threshold(0)
    , time_per_order(0)  {
  (void)_alloc;
    }



   typedef int8_t _offline_recognise_start_type;
  _offline_recognise_start_type offline_recognise_start;

   typedef int8_t _confidence_threshold_type;
  _confidence_threshold_type confidence_threshold;

   typedef int8_t _time_per_order_type;
  _time_per_order_type time_per_order;





  typedef boost::shared_ptr< ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetOfflineResultRequest_

typedef ::xf_mic_asr_offline::GetOfflineResultRequest_<std::allocator<void> > GetOfflineResultRequest;

typedef boost::shared_ptr< ::xf_mic_asr_offline::GetOfflineResultRequest > GetOfflineResultRequestPtr;
typedef boost::shared_ptr< ::xf_mic_asr_offline::GetOfflineResultRequest const> GetOfflineResultRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator1> & lhs, const ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator2> & rhs)
{
  return lhs.offline_recognise_start == rhs.offline_recognise_start &&
    lhs.confidence_threshold == rhs.confidence_threshold &&
    lhs.time_per_order == rhs.time_per_order;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator1> & lhs, const ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xf_mic_asr_offline

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "820f3ed766cd949404133c9745d8edac";
  }

  static const char* value(const ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x820f3ed766cd9494ULL;
  static const uint64_t static_value2 = 0x04133c9745d8edacULL;
};

template<class ContainerAllocator>
struct DataType< ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xf_mic_asr_offline/GetOfflineResultRequest";
  }

  static const char* value(const ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 offline_recognise_start\n"
"int8 confidence_threshold \n"
"int8 time_per_order\n"
;
  }

  static const char* value(const ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offline_recognise_start);
      stream.next(m.confidence_threshold);
      stream.next(m.time_per_order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetOfflineResultRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xf_mic_asr_offline::GetOfflineResultRequest_<ContainerAllocator>& v)
  {
    s << indent << "offline_recognise_start: ";
    Printer<int8_t>::stream(s, indent + "  ", v.offline_recognise_start);
    s << indent << "confidence_threshold: ";
    Printer<int8_t>::stream(s, indent + "  ", v.confidence_threshold);
    s << indent << "time_per_order: ";
    Printer<int8_t>::stream(s, indent + "  ", v.time_per_order);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XF_MIC_ASR_OFFLINE_MESSAGE_GETOFFLINERESULTREQUEST_H
