<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="M_PI"                   value="3.1415926535897931"/>
  <xacro:property name="depth_camera_name"      default="camera" />
  <xacro:property name="depth_camera_link_mass" value="0.200" />
  <xacro:property name="depth_camera_link_w"    value="0.1644" />
  <xacro:property name="depth_camera_link_h"    value="0.05" />
  <xacro:property name="depth_camera_link_d"    value="0.051" />
  <link
    name="${depth_camera_name}_link">
    <xacro:box_inertial m="${depth_camera_link_mass}" w="${depth_camera_link_w}" h="${depth_camera_link_h}" d="${depth_camera_link_d}"/>
    <visual>
      <origin xyz="0 0 0.08" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://jetauto_description/meshes/pro/depth_camera_link.stl" />
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${-depth_camera_link_h/2.0 + 0.015}" rpy="-${M_PI/2} 0 ${M_PI/2}" />
      <geometry>
        <box size="${depth_camera_link_w} ${depth_camera_link_h} ${depth_camera_link_d}" />
      </geometry>
    </collision>
  </link>
  <joint
    name="${depth_camera_name}_joint"
    type="fixed">
    <origin xyz="-0.13068 0 0.43671" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="${depth_camera_name}_link" />
    <axis xyz="0 0 0" />
  </joint>

  <link name="${depth_camera_name}_frame" />
  <joint
    name="${depth_camera_name}_joint_sim"
    type="fixed">
    <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
    <parent link="${depth_camera_name}_link" />
    <child link="${depth_camera_name}_frame" />
  </joint>
</robot>
