// Generated by gencpp from file jetauto_interfaces/ColorsInfo.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_COLORSINFO_H
#define JETAUTO_INTERFACES_MESSAGE_COLORSINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <jetauto_interfaces/ColorInfo.h>

namespace jetauto_interfaces
{
template <class ContainerAllocator>
struct ColorsInfo_
{
  typedef ColorsInfo_<ContainerAllocator> Type;

  ColorsInfo_()
    : data()  {
    }
  ColorsInfo_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::jetauto_interfaces::ColorInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::jetauto_interfaces::ColorInfo_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ColorsInfo_

typedef ::jetauto_interfaces::ColorsInfo_<std::allocator<void> > ColorsInfo;

typedef boost::shared_ptr< ::jetauto_interfaces::ColorsInfo > ColorsInfoPtr;
typedef boost::shared_ptr< ::jetauto_interfaces::ColorsInfo const> ColorsInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetauto_interfaces::ColorsInfo_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::ColorsInfo_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetauto_interfaces::ColorsInfo_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::ColorsInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetauto_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c5294caa84fe6818ade3c3510c74950";
  }

  static const char* value(const ::jetauto_interfaces::ColorsInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c5294caa84fe681ULL;
  static const uint64_t static_value2 = 0x8ade3c3510c74950ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/ColorsInfo";
  }

  static const char* value(const ::jetauto_interfaces::ColorsInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return " jetauto_interfaces/ColorInfo[] data\n"
"\n"
"================================================================================\n"
"MSG: jetauto_interfaces/ColorInfo\n"
"string color\n"
"int32 width\n"
"int32 height\n"
"int32 x\n"
"int32 y\n"
"int32 radius\n"
"int32 angle\n"
;
  }

  static const char* value(const ::jetauto_interfaces::ColorsInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColorsInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetauto_interfaces::ColorsInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetauto_interfaces::ColorsInfo_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::jetauto_interfaces::ColorInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_COLORSINFO_H
