// Generated by gencpp from file jetauto_interfaces/Float64List.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_FLOAT64LIST_H
#define JETAUTO_INTERFACES_MESSAGE_FLOAT64LIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetauto_interfaces
{
template <class ContainerAllocator>
struct Float64List_
{
  typedef Float64List_<ContainerAllocator> Type;

  Float64List_()
    : data()  {
    }
  Float64List_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::jetauto_interfaces::Float64List_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetauto_interfaces::Float64List_<ContainerAllocator> const> ConstPtr;

}; // struct Float64List_

typedef ::jetauto_interfaces::Float64List_<std::allocator<void> > Float64List;

typedef boost::shared_ptr< ::jetauto_interfaces::Float64List > Float64ListPtr;
typedef boost::shared_ptr< ::jetauto_interfaces::Float64List const> Float64ListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetauto_interfaces::Float64List_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetauto_interfaces::Float64List_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetauto_interfaces::Float64List_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::Float64List_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetauto_interfaces::Float64List_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::Float64List_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetauto_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::Float64List_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::Float64List_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::Float64List_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::Float64List_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::Float64List_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::Float64List_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetauto_interfaces::Float64List_<ContainerAllocator> >
{
  static const char* value()
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const ::jetauto_interfaces::Float64List_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x788898178a3da2c3ULL;
  static const uint64_t static_value2 = 0x718461eecda8f714ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetauto_interfaces::Float64List_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/Float64List";
  }

  static const char* value(const ::jetauto_interfaces::Float64List_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetauto_interfaces::Float64List_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] data\n"
;
  }

  static const char* value(const ::jetauto_interfaces::Float64List_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetauto_interfaces::Float64List_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Float64List_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetauto_interfaces::Float64List_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetauto_interfaces::Float64List_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_FLOAT64LIST_H
