// Generated by gencpp from file jetauto_interfaces/Point2D.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_POINT2D_H
#define JETAUTO_INTERFACES_MESSAGE_POINT2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetauto_interfaces
{
template <class ContainerAllocator>
struct Point2D_
{
  typedef Point2D_<ContainerAllocator> Type;

  Point2D_()
    : width(0)
    , height(0)
    , x(0)
    , y(0)  {
    }
  Point2D_(const ContainerAllocator& _alloc)
    : width(0)
    , height(0)
    , x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int32_t _width_type;
  _width_type width;

   typedef int32_t _height_type;
  _height_type height;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::jetauto_interfaces::Point2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetauto_interfaces::Point2D_<ContainerAllocator> const> ConstPtr;

}; // struct Point2D_

typedef ::jetauto_interfaces::Point2D_<std::allocator<void> > Point2D;

typedef boost::shared_ptr< ::jetauto_interfaces::Point2D > Point2DPtr;
typedef boost::shared_ptr< ::jetauto_interfaces::Point2D const> Point2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetauto_interfaces::Point2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetauto_interfaces::Point2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetauto_interfaces::Point2D_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::Point2D_<ContainerAllocator2> & rhs)
{
  return lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetauto_interfaces::Point2D_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::Point2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetauto_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::Point2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::Point2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::Point2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::Point2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::Point2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::Point2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetauto_interfaces::Point2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9719c26e1c94e945e9c9bae938c14241";
  }

  static const char* value(const ::jetauto_interfaces::Point2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9719c26e1c94e945ULL;
  static const uint64_t static_value2 = 0xe9c9bae938c14241ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetauto_interfaces::Point2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/Point2D";
  }

  static const char* value(const ::jetauto_interfaces::Point2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetauto_interfaces::Point2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 width\n"
"int32 height\n"
"int32 x\n"
"int32 y\n"
;
  }

  static const char* value(const ::jetauto_interfaces::Point2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetauto_interfaces::Point2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetauto_interfaces::Point2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetauto_interfaces::Point2D_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_POINT2D_H
