// Generated by gencpp from file jetauto_interfaces/ROI.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_ROI_H
#define JETAUTO_INTERFACES_MESSAGE_ROI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetauto_interfaces
{
template <class ContainerAllocator>
struct ROI_
{
  typedef ROI_<ContainerAllocator> Type;

  ROI_()
    : y_min(0)
    , y_max(0)
    , x_min(0)
    , x_max(0)
    , scale(0.0)  {
    }
  ROI_(const ContainerAllocator& _alloc)
    : y_min(0)
    , y_max(0)
    , x_min(0)
    , x_max(0)
    , scale(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _y_min_type;
  _y_min_type y_min;

   typedef int16_t _y_max_type;
  _y_max_type y_max;

   typedef int16_t _x_min_type;
  _x_min_type x_min;

   typedef int16_t _x_max_type;
  _x_max_type x_max;

   typedef float _scale_type;
  _scale_type scale;





  typedef boost::shared_ptr< ::jetauto_interfaces::ROI_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetauto_interfaces::ROI_<ContainerAllocator> const> ConstPtr;

}; // struct ROI_

typedef ::jetauto_interfaces::ROI_<std::allocator<void> > ROI;

typedef boost::shared_ptr< ::jetauto_interfaces::ROI > ROIPtr;
typedef boost::shared_ptr< ::jetauto_interfaces::ROI const> ROIConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetauto_interfaces::ROI_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetauto_interfaces::ROI_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetauto_interfaces::ROI_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::ROI_<ContainerAllocator2> & rhs)
{
  return lhs.y_min == rhs.y_min &&
    lhs.y_max == rhs.y_max &&
    lhs.x_min == rhs.x_min &&
    lhs.x_max == rhs.x_max &&
    lhs.scale == rhs.scale;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetauto_interfaces::ROI_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::ROI_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetauto_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::ROI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::ROI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::ROI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::ROI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::ROI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::ROI_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetauto_interfaces::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaf833fe38b074210f5cb78ebd4c1035";
  }

  static const char* value(const ::jetauto_interfaces::ROI_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaf833fe38b07421ULL;
  static const uint64_t static_value2 = 0x0f5cb78ebd4c1035ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetauto_interfaces::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/ROI";
  }

  static const char* value(const ::jetauto_interfaces::ROI_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetauto_interfaces::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 y_min\n"
"int16 y_max\n"
"int16 x_min\n"
"int16 x_max\n"
"float32 scale\n"
;
  }

  static const char* value(const ::jetauto_interfaces::ROI_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetauto_interfaces::ROI_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.y_min);
      stream.next(m.y_max);
      stream.next(m.x_min);
      stream.next(m.x_max);
      stream.next(m.scale);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ROI_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetauto_interfaces::ROI_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetauto_interfaces::ROI_<ContainerAllocator>& v)
  {
    s << indent << "y_min: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y_min);
    s << indent << "y_max: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y_max);
    s << indent << "x_min: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x_min);
    s << indent << "x_max: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x_max);
    s << indent << "scale: ";
    Printer<float>::stream(s, indent + "  ", v.scale);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_ROI_H
