// Generated by gencpp from file jetauto_interfaces/SetCircleROI.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_SETCIRCLEROI_H
#define JETAUTO_INTERFACES_MESSAGE_SETCIRCLEROI_H

#include <ros/service_traits.h>


#include <jetauto_interfaces/SetCircleROIRequest.h>
#include <jetauto_interfaces/SetCircleROIResponse.h>


namespace jetauto_interfaces
{

struct SetCircleROI
{

typedef SetCircleROIRequest Request;
typedef SetCircleROIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCircleROI
} // namespace jetauto_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetauto_interfaces::SetCircleROI > {
  static const char* value()
  {
    return "eff5af47147109863af37e6078d2eeb8";
  }

  static const char* value(const ::jetauto_interfaces::SetCircleROI&) { return value(); }
};

template<>
struct DataType< ::jetauto_interfaces::SetCircleROI > {
  static const char* value()
  {
    return "jetauto_interfaces/SetCircleROI";
  }

  static const char* value(const ::jetauto_interfaces::SetCircleROI&) { return value(); }
};


// service_traits::MD5Sum< ::jetauto_interfaces::SetCircleROIRequest> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetCircleROI >
template<>
struct MD5Sum< ::jetauto_interfaces::SetCircleROIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetCircleROI >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetCircleROIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetCircleROIRequest> should match
// service_traits::DataType< ::jetauto_interfaces::SetCircleROI >
template<>
struct DataType< ::jetauto_interfaces::SetCircleROIRequest>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetCircleROI >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetCircleROIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetauto_interfaces::SetCircleROIResponse> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetCircleROI >
template<>
struct MD5Sum< ::jetauto_interfaces::SetCircleROIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetCircleROI >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetCircleROIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetCircleROIResponse> should match
// service_traits::DataType< ::jetauto_interfaces::SetCircleROI >
template<>
struct DataType< ::jetauto_interfaces::SetCircleROIResponse>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetCircleROI >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetCircleROIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_SETCIRCLEROI_H
