// Generated by gencpp from file jetauto_interfaces/SetColorDetectParam.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_SETCOLORDETECTPARAM_H
#define JETAUTO_INTERFACES_MESSAGE_SETCOLORDETECTPARAM_H

#include <ros/service_traits.h>


#include <jetauto_interfaces/SetColorDetectParamRequest.h>
#include <jetauto_interfaces/SetColorDetectParamResponse.h>


namespace jetauto_interfaces
{

struct SetColorDetectParam
{

typedef SetColorDetectParamRequest Request;
typedef SetColorDetectParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetColorDetectParam
} // namespace jetauto_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetauto_interfaces::SetColorDetectParam > {
  static const char* value()
  {
    return "0ec73f9b73674c15d92cf45372dbab3f";
  }

  static const char* value(const ::jetauto_interfaces::SetColorDetectParam&) { return value(); }
};

template<>
struct DataType< ::jetauto_interfaces::SetColorDetectParam > {
  static const char* value()
  {
    return "jetauto_interfaces/SetColorDetectParam";
  }

  static const char* value(const ::jetauto_interfaces::SetColorDetectParam&) { return value(); }
};


// service_traits::MD5Sum< ::jetauto_interfaces::SetColorDetectParamRequest> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetColorDetectParam >
template<>
struct MD5Sum< ::jetauto_interfaces::SetColorDetectParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetColorDetectParam >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetColorDetectParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetColorDetectParamRequest> should match
// service_traits::DataType< ::jetauto_interfaces::SetColorDetectParam >
template<>
struct DataType< ::jetauto_interfaces::SetColorDetectParamRequest>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetColorDetectParam >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetColorDetectParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetauto_interfaces::SetColorDetectParamResponse> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetColorDetectParam >
template<>
struct MD5Sum< ::jetauto_interfaces::SetColorDetectParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetColorDetectParam >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetColorDetectParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetColorDetectParamResponse> should match
// service_traits::DataType< ::jetauto_interfaces::SetColorDetectParam >
template<>
struct DataType< ::jetauto_interfaces::SetColorDetectParamResponse>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetColorDetectParam >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetColorDetectParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_SETCOLORDETECTPARAM_H
