// Generated by gencpp from file jetauto_interfaces/SetJointValue.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_SETJOINTVALUE_H
#define JETAUTO_INTERFACES_MESSAGE_SETJOINTVALUE_H

#include <ros/service_traits.h>


#include <jetauto_interfaces/SetJointValueRequest.h>
#include <jetauto_interfaces/SetJointValueResponse.h>


namespace jetauto_interfaces
{

struct SetJointValue
{

typedef SetJointValueRequest Request;
typedef SetJointValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointValue
} // namespace jetauto_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetauto_interfaces::SetJointValue > {
  static const char* value()
  {
    return "f30e2e31fba61d3992775965b6a52966";
  }

  static const char* value(const ::jetauto_interfaces::SetJointValue&) { return value(); }
};

template<>
struct DataType< ::jetauto_interfaces::SetJointValue > {
  static const char* value()
  {
    return "jetauto_interfaces/SetJointValue";
  }

  static const char* value(const ::jetauto_interfaces::SetJointValue&) { return value(); }
};


// service_traits::MD5Sum< ::jetauto_interfaces::SetJointValueRequest> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetJointValue >
template<>
struct MD5Sum< ::jetauto_interfaces::SetJointValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetJointValue >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetJointValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetJointValueRequest> should match
// service_traits::DataType< ::jetauto_interfaces::SetJointValue >
template<>
struct DataType< ::jetauto_interfaces::SetJointValueRequest>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetJointValue >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetJointValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetauto_interfaces::SetJointValueResponse> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetJointValue >
template<>
struct MD5Sum< ::jetauto_interfaces::SetJointValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetJointValue >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetJointValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetJointValueResponse> should match
// service_traits::DataType< ::jetauto_interfaces::SetJointValue >
template<>
struct DataType< ::jetauto_interfaces::SetJointValueResponse>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetJointValue >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetJointValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_SETJOINTVALUE_H
