// Generated by gencpp from file jetauto_interfaces/SetPointRequest.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_SETPOINTREQUEST_H
#define JETAUTO_INTERFACES_MESSAGE_SETPOINTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace jetauto_interfaces
{
template <class ContainerAllocator>
struct SetPointRequest_
{
  typedef SetPointRequest_<ContainerAllocator> Type;

  SetPointRequest_()
    : data()  {
    }
  SetPointRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPointRequest_

typedef ::jetauto_interfaces::SetPointRequest_<std::allocator<void> > SetPointRequest;

typedef boost::shared_ptr< ::jetauto_interfaces::SetPointRequest > SetPointRequestPtr;
typedef boost::shared_ptr< ::jetauto_interfaces::SetPointRequest const> SetPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetauto_interfaces::SetPointRequest_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::SetPointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetauto_interfaces::SetPointRequest_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::SetPointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetauto_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "390cbff96d168abc35f84f5ed0728288";
  }

  static const char* value(const ::jetauto_interfaces::SetPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x390cbff96d168abcULL;
  static const uint64_t static_value2 = 0x35f84f5ed0728288ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/SetPointRequest";
  }

  static const char* value(const ::jetauto_interfaces::SetPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::jetauto_interfaces::SetPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetauto_interfaces::SetPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetauto_interfaces::SetPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_SETPOINTREQUEST_H
