// Generated by gencpp from file jetauto_interfaces/SetStringList.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_SETSTRINGLIST_H
#define JETAUTO_INTERFACES_MESSAGE_SETSTRINGLIST_H

#include <ros/service_traits.h>


#include <jetauto_interfaces/SetStringListRequest.h>
#include <jetauto_interfaces/SetStringListResponse.h>


namespace jetauto_interfaces
{

struct SetStringList
{

typedef SetStringListRequest Request;
typedef SetStringListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetStringList
} // namespace jetauto_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetauto_interfaces::SetStringList > {
  static const char* value()
  {
    return "1f446846928755f68919cab6862f6368";
  }

  static const char* value(const ::jetauto_interfaces::SetStringList&) { return value(); }
};

template<>
struct DataType< ::jetauto_interfaces::SetStringList > {
  static const char* value()
  {
    return "jetauto_interfaces/SetStringList";
  }

  static const char* value(const ::jetauto_interfaces::SetStringList&) { return value(); }
};


// service_traits::MD5Sum< ::jetauto_interfaces::SetStringListRequest> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetStringList >
template<>
struct MD5Sum< ::jetauto_interfaces::SetStringListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetStringList >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetStringListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetStringListRequest> should match
// service_traits::DataType< ::jetauto_interfaces::SetStringList >
template<>
struct DataType< ::jetauto_interfaces::SetStringListRequest>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetStringList >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetStringListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetauto_interfaces::SetStringListResponse> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetStringList >
template<>
struct MD5Sum< ::jetauto_interfaces::SetStringListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetStringList >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetStringListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetStringListResponse> should match
// service_traits::DataType< ::jetauto_interfaces::SetStringList >
template<>
struct DataType< ::jetauto_interfaces::SetStringListResponse>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetStringList >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetStringListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_SETSTRINGLIST_H
