(cl:defpackage hiwonder_servo_msgs-srv
  (:use )
  (:export
   "GETSERVOSTATE"
   "<GETSERVOSTATE-REQUEST>"
   "GETSERVOSTATE-REQUEST"
   "<GETSERVOSTATE-RESPONSE>"
   "GETSERVOSTATE-RESPONSE"
   "SETREADTIMEOUT"
   "<SETREADTIMEOUT-REQUEST>"
   "SETREADTIMEOUT-REQUEST"
   "<SETREADTIMEOUT-RESPONSE>"
   "SETREADTIMEOUT-RESPONSE"
  ))

