controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - r_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: gripper
    pose: close