// Generated by gencpp from file hiwonder_servo_msgs/GetServoStateResponse.msg
// DO NOT EDIT!


#ifndef HIWONDER_SERVO_MSGS_MESSAGE_GETSERVOSTATERESPONSE_H
#define HIWONDER_SERVO_MSGS_MESSAGE_GETSERVOSTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_servo_msgs
{
template <class ContainerAllocator>
struct GetServoStateResponse_
{
  typedef GetServoStateResponse_<ContainerAllocator> Type;

  GetServoStateResponse_()
    : success(false)
    , value()  {
    }
  GetServoStateResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetServoStateResponse_

typedef ::hiwonder_servo_msgs::GetServoStateResponse_<std::allocator<void> > GetServoStateResponse;

typedef boost::shared_ptr< ::hiwonder_servo_msgs::GetServoStateResponse > GetServoStateResponsePtr;
typedef boost::shared_ptr< ::hiwonder_servo_msgs::GetServoStateResponse const> GetServoStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_servo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22a20264adf63d46791b03ff18adb645";
  }

  static const char* value(const ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22a20264adf63d46ULL;
  static const uint64_t static_value2 = 0x791b03ff18adb645ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_servo_msgs/GetServoStateResponse";
  }

  static const char* value(const ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"float32[] value\n"
"\n"
;
  }

  static const char* value(const ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetServoStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_servo_msgs::GetServoStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_SERVO_MSGS_MESSAGE_GETSERVOSTATERESPONSE_H
