// Generated by gencpp from file hiwonder_servo_msgs/SetReadTimeoutResponse.msg
// DO NOT EDIT!


#ifndef HIWONDER_SERVO_MSGS_MESSAGE_SETREADTIMEOUTRESPONSE_H
#define HIWONDER_SERVO_MSGS_MESSAGE_SETREADTIMEOUTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_servo_msgs
{
template <class ContainerAllocator>
struct SetReadTimeoutResponse_
{
  typedef SetReadTimeoutResponse_<ContainerAllocator> Type;

  SetReadTimeoutResponse_()
    : success(false)
    , result()  {
    }
  SetReadTimeoutResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , result(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetReadTimeoutResponse_

typedef ::hiwonder_servo_msgs::SetReadTimeoutResponse_<std::allocator<void> > SetReadTimeoutResponse;

typedef boost::shared_ptr< ::hiwonder_servo_msgs::SetReadTimeoutResponse > SetReadTimeoutResponsePtr;
typedef boost::shared_ptr< ::hiwonder_servo_msgs::SetReadTimeoutResponse const> SetReadTimeoutResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_servo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c4b99d3c45e94cd751d81f8afc890bc";
  }

  static const char* value(const ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c4b99d3c45e94cdULL;
  static const uint64_t static_value2 = 0x751d81f8afc890bcULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_servo_msgs/SetReadTimeoutResponse";
  }

  static const char* value(const ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string result\n"
"\n"
;
  }

  static const char* value(const ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetReadTimeoutResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_servo_msgs::SetReadTimeoutResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_SERVO_MSGS_MESSAGE_SETREADTIMEOUTRESPONSE_H
