// Generated by gencpp from file hiwonder_servo_msgs/SetReadTimeoutRequest.msg
// DO NOT EDIT!


#ifndef HIWONDER_SERVO_MSGS_MESSAGE_SETREADTIMEOUTREQUEST_H
#define HIWONDER_SERVO_MSGS_MESSAGE_SETREADTIMEOUTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_servo_msgs
{
template <class ContainerAllocator>
struct SetReadTimeoutRequest_
{
  typedef SetReadTimeoutRequest_<ContainerAllocator> Type;

  SetReadTimeoutRequest_()
    : times(0)  {
    }
  SetReadTimeoutRequest_(const ContainerAllocator& _alloc)
    : times(0)  {
  (void)_alloc;
    }



   typedef uint8_t _times_type;
  _times_type times;





  typedef boost::shared_ptr< ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetReadTimeoutRequest_

typedef ::hiwonder_servo_msgs::SetReadTimeoutRequest_<std::allocator<void> > SetReadTimeoutRequest;

typedef boost::shared_ptr< ::hiwonder_servo_msgs::SetReadTimeoutRequest > SetReadTimeoutRequestPtr;
typedef boost::shared_ptr< ::hiwonder_servo_msgs::SetReadTimeoutRequest const> SetReadTimeoutRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator2> & rhs)
{
  return lhs.times == rhs.times;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_servo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bb367c5d3cf2a006464e171a8a8e45b";
  }

  static const char* value(const ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bb367c5d3cf2a00ULL;
  static const uint64_t static_value2 = 0x6464e171a8a8e45bULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_servo_msgs/SetReadTimeoutRequest";
  }

  static const char* value(const ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 times\n"
;
  }

  static const char* value(const ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.times);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetReadTimeoutRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_servo_msgs::SetReadTimeoutRequest_<ContainerAllocator>& v)
  {
    s << indent << "times: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.times);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_SERVO_MSGS_MESSAGE_SETREADTIMEOUTREQUEST_H
