// Generated by gencpp from file hiwonder_servo_msgs/GetServoState.msg
// DO NOT EDIT!


#ifndef HIWONDER_SERVO_MSGS_MESSAGE_GETSERVOSTATE_H
#define HIWONDER_SERVO_MSGS_MESSAGE_GETSERVOSTATE_H

#include <ros/service_traits.h>


#include <hiwonder_servo_msgs/GetServoStateRequest.h>
#include <hiwonder_servo_msgs/GetServoStateResponse.h>


namespace hiwonder_servo_msgs
{

struct GetServoState
{

typedef GetServoStateRequest Request;
typedef GetServoStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetServoState
} // namespace hiwonder_servo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_servo_msgs::GetServoState > {
  static const char* value()
  {
    return "3f2b7dfd5e7d17f9fb64e9e86bb09ef2";
  }

  static const char* value(const ::hiwonder_servo_msgs::GetServoState&) { return value(); }
};

template<>
struct DataType< ::hiwonder_servo_msgs::GetServoState > {
  static const char* value()
  {
    return "hiwonder_servo_msgs/GetServoState";
  }

  static const char* value(const ::hiwonder_servo_msgs::GetServoState&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_servo_msgs::GetServoStateRequest> should match
// service_traits::MD5Sum< ::hiwonder_servo_msgs::GetServoState >
template<>
struct MD5Sum< ::hiwonder_servo_msgs::GetServoStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_servo_msgs::GetServoState >::value();
  }
  static const char* value(const ::hiwonder_servo_msgs::GetServoStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_servo_msgs::GetServoStateRequest> should match
// service_traits::DataType< ::hiwonder_servo_msgs::GetServoState >
template<>
struct DataType< ::hiwonder_servo_msgs::GetServoStateRequest>
{
  static const char* value()
  {
    return DataType< ::hiwonder_servo_msgs::GetServoState >::value();
  }
  static const char* value(const ::hiwonder_servo_msgs::GetServoStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_servo_msgs::GetServoStateResponse> should match
// service_traits::MD5Sum< ::hiwonder_servo_msgs::GetServoState >
template<>
struct MD5Sum< ::hiwonder_servo_msgs::GetServoStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_servo_msgs::GetServoState >::value();
  }
  static const char* value(const ::hiwonder_servo_msgs::GetServoStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_servo_msgs::GetServoStateResponse> should match
// service_traits::DataType< ::hiwonder_servo_msgs::GetServoState >
template<>
struct DataType< ::hiwonder_servo_msgs::GetServoStateResponse>
{
  static const char* value()
  {
    return DataType< ::hiwonder_servo_msgs::GetServoState >::value();
  }
  static const char* value(const ::hiwonder_servo_msgs::GetServoStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_SERVO_MSGS_MESSAGE_GETSERVOSTATE_H
