// Generated by gencpp from file hiwonder_servo_msgs/GetServoStateRequest.msg
// DO NOT EDIT!


#ifndef HIWONDER_SERVO_MSGS_MESSAGE_GETSERVOSTATEREQUEST_H
#define HIWONDER_SERVO_MSGS_MESSAGE_GETSERVOSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_servo_msgs
{
template <class ContainerAllocator>
struct GetServoStateRequest_
{
  typedef GetServoStateRequest_<ContainerAllocator> Type;

  GetServoStateRequest_()
    : cmd()
    , id(0)  {
    }
  GetServoStateRequest_(const ContainerAllocator& _alloc)
    : cmd(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cmd_type;
  _cmd_type cmd;

   typedef int16_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetServoStateRequest_

typedef ::hiwonder_servo_msgs::GetServoStateRequest_<std::allocator<void> > GetServoStateRequest;

typedef boost::shared_ptr< ::hiwonder_servo_msgs::GetServoStateRequest > GetServoStateRequestPtr;
typedef boost::shared_ptr< ::hiwonder_servo_msgs::GetServoStateRequest const> GetServoStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_servo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "099e4328c8a015bbe8258f05aae50da4";
  }

  static const char* value(const ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x099e4328c8a015bbULL;
  static const uint64_t static_value2 = 0xe8258f05aae50da4ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_servo_msgs/GetServoStateRequest";
  }

  static const char* value(const ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string cmd\n"
"int16 id\n"
;
  }

  static const char* value(const ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetServoStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_servo_msgs::GetServoStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cmd);
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_SERVO_MSGS_MESSAGE_GETSERVOSTATEREQUEST_H
