// Generated by gencpp from file jetauto_interfaces/GetPose.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_GETPOSE_H
#define JETAUTO_INTERFACES_MESSAGE_GETPOSE_H

#include <ros/service_traits.h>


#include <jetauto_interfaces/GetPoseRequest.h>
#include <jetauto_interfaces/GetPoseResponse.h>


namespace jetauto_interfaces
{

struct GetPose
{

typedef GetPoseRequest Request;
typedef GetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPose
} // namespace jetauto_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetauto_interfaces::GetPose > {
  static const char* value()
  {
    return "15f95f5538fad94dd79708adc832f5c7";
  }

  static const char* value(const ::jetauto_interfaces::GetPose&) { return value(); }
};

template<>
struct DataType< ::jetauto_interfaces::GetPose > {
  static const char* value()
  {
    return "jetauto_interfaces/GetPose";
  }

  static const char* value(const ::jetauto_interfaces::GetPose&) { return value(); }
};


// service_traits::MD5Sum< ::jetauto_interfaces::GetPoseRequest> should match
// service_traits::MD5Sum< ::jetauto_interfaces::GetPose >
template<>
struct MD5Sum< ::jetauto_interfaces::GetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::GetPose >::value();
  }
  static const char* value(const ::jetauto_interfaces::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::GetPoseRequest> should match
// service_traits::DataType< ::jetauto_interfaces::GetPose >
template<>
struct DataType< ::jetauto_interfaces::GetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::GetPose >::value();
  }
  static const char* value(const ::jetauto_interfaces::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetauto_interfaces::GetPoseResponse> should match
// service_traits::MD5Sum< ::jetauto_interfaces::GetPose >
template<>
struct MD5Sum< ::jetauto_interfaces::GetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::GetPose >::value();
  }
  static const char* value(const ::jetauto_interfaces::GetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::GetPoseResponse> should match
// service_traits::DataType< ::jetauto_interfaces::GetPose >
template<>
struct DataType< ::jetauto_interfaces::GetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::GetPose >::value();
  }
  static const char* value(const ::jetauto_interfaces::GetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_GETPOSE_H
