// Generated by gencpp from file jetauto_interfaces/LineROI.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_LINEROI_H
#define JETAUTO_INTERFACES_MESSAGE_LINEROI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <jetauto_interfaces/ROI.h>
#include <jetauto_interfaces/ROI.h>
#include <jetauto_interfaces/ROI.h>

namespace jetauto_interfaces
{
template <class ContainerAllocator>
struct LineROI_
{
  typedef LineROI_<ContainerAllocator> Type;

  LineROI_()
    : roi_up()
    , roi_center()
    , roi_down()  {
    }
  LineROI_(const ContainerAllocator& _alloc)
    : roi_up(_alloc)
    , roi_center(_alloc)
    , roi_down(_alloc)  {
  (void)_alloc;
    }



   typedef  ::jetauto_interfaces::ROI_<ContainerAllocator>  _roi_up_type;
  _roi_up_type roi_up;

   typedef  ::jetauto_interfaces::ROI_<ContainerAllocator>  _roi_center_type;
  _roi_center_type roi_center;

   typedef  ::jetauto_interfaces::ROI_<ContainerAllocator>  _roi_down_type;
  _roi_down_type roi_down;





  typedef boost::shared_ptr< ::jetauto_interfaces::LineROI_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetauto_interfaces::LineROI_<ContainerAllocator> const> ConstPtr;

}; // struct LineROI_

typedef ::jetauto_interfaces::LineROI_<std::allocator<void> > LineROI;

typedef boost::shared_ptr< ::jetauto_interfaces::LineROI > LineROIPtr;
typedef boost::shared_ptr< ::jetauto_interfaces::LineROI const> LineROIConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetauto_interfaces::LineROI_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetauto_interfaces::LineROI_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetauto_interfaces::LineROI_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::LineROI_<ContainerAllocator2> & rhs)
{
  return lhs.roi_up == rhs.roi_up &&
    lhs.roi_center == rhs.roi_center &&
    lhs.roi_down == rhs.roi_down;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetauto_interfaces::LineROI_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::LineROI_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetauto_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::LineROI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::LineROI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::LineROI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::LineROI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::LineROI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::LineROI_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetauto_interfaces::LineROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b196228fae7ce5d6afb589f8af99c676";
  }

  static const char* value(const ::jetauto_interfaces::LineROI_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb196228fae7ce5d6ULL;
  static const uint64_t static_value2 = 0xafb589f8af99c676ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetauto_interfaces::LineROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/LineROI";
  }

  static const char* value(const ::jetauto_interfaces::LineROI_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetauto_interfaces::LineROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/ROI roi_up\n"
"jetauto_interfaces/ROI roi_center\n"
"jetauto_interfaces/ROI roi_down\n"
"\n"
"================================================================================\n"
"MSG: jetauto_interfaces/ROI\n"
"int16 y_min\n"
"int16 y_max\n"
"int16 x_min\n"
"int16 x_max\n"
"float32 scale\n"
;
  }

  static const char* value(const ::jetauto_interfaces::LineROI_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetauto_interfaces::LineROI_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roi_up);
      stream.next(m.roi_center);
      stream.next(m.roi_down);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineROI_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetauto_interfaces::LineROI_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetauto_interfaces::LineROI_<ContainerAllocator>& v)
  {
    s << indent << "roi_up: ";
    s << std::endl;
    Printer< ::jetauto_interfaces::ROI_<ContainerAllocator> >::stream(s, indent + "  ", v.roi_up);
    s << indent << "roi_center: ";
    s << std::endl;
    Printer< ::jetauto_interfaces::ROI_<ContainerAllocator> >::stream(s, indent + "  ", v.roi_center);
    s << indent << "roi_down: ";
    s << std::endl;
    Printer< ::jetauto_interfaces::ROI_<ContainerAllocator> >::stream(s, indent + "  ", v.roi_down);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_LINEROI_H
