// Generated by gencpp from file jetauto_interfaces/ObjectsInfo.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_OBJECTSINFO_H
#define JETAUTO_INTERFACES_MESSAGE_OBJECTSINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <jetauto_interfaces/ObjectInfo.h>

namespace jetauto_interfaces
{
template <class ContainerAllocator>
struct ObjectsInfo_
{
  typedef ObjectsInfo_<ContainerAllocator> Type;

  ObjectsInfo_()
    : objects()  {
    }
  ObjectsInfo_(const ContainerAllocator& _alloc)
    : objects(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::jetauto_interfaces::ObjectInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::jetauto_interfaces::ObjectInfo_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectsInfo_

typedef ::jetauto_interfaces::ObjectsInfo_<std::allocator<void> > ObjectsInfo;

typedef boost::shared_ptr< ::jetauto_interfaces::ObjectsInfo > ObjectsInfoPtr;
typedef boost::shared_ptr< ::jetauto_interfaces::ObjectsInfo const> ObjectsInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator2> & rhs)
{
  return lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetauto_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "257af89367afa3cd0032cdb5a0607c8b";
  }

  static const char* value(const ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x257af89367afa3cdULL;
  static const uint64_t static_value2 = 0x0032cdb5a0607c8bULL;
};

template<class ContainerAllocator>
struct DataType< ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/ObjectsInfo";
  }

  static const char* value(const ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/ObjectInfo[] objects\n"
"\n"
"================================================================================\n"
"MSG: jetauto_interfaces/ObjectInfo\n"
"string class_name\n"
"int32[] box\n"
"float32 score\n"
;
  }

  static const char* value(const ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectsInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetauto_interfaces::ObjectsInfo_<ContainerAllocator>& v)
  {
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::jetauto_interfaces::ObjectInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_OBJECTSINFO_H
