// Generated by gencpp from file jetauto_interfaces/Points.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_POINTS_H
#define JETAUTO_INTERFACES_MESSAGE_POINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <jetauto_interfaces/PixelPosition.h>

namespace jetauto_interfaces
{
template <class ContainerAllocator>
struct Points_
{
  typedef Points_<ContainerAllocator> Type;

  Points_()
    : points()  {
    }
  Points_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::jetauto_interfaces::PixelPosition_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::jetauto_interfaces::PixelPosition_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::jetauto_interfaces::Points_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetauto_interfaces::Points_<ContainerAllocator> const> ConstPtr;

}; // struct Points_

typedef ::jetauto_interfaces::Points_<std::allocator<void> > Points;

typedef boost::shared_ptr< ::jetauto_interfaces::Points > PointsPtr;
typedef boost::shared_ptr< ::jetauto_interfaces::Points const> PointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetauto_interfaces::Points_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetauto_interfaces::Points_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetauto_interfaces::Points_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::Points_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetauto_interfaces::Points_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::Points_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetauto_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::Points_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::Points_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::Points_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::Points_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::Points_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::Points_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetauto_interfaces::Points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f02263beef99aa03117a577a3eb879d";
  }

  static const char* value(const ::jetauto_interfaces::Points_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f02263beef99aa0ULL;
  static const uint64_t static_value2 = 0x3117a577a3eb879dULL;
};

template<class ContainerAllocator>
struct DataType< ::jetauto_interfaces::Points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/Points";
  }

  static const char* value(const ::jetauto_interfaces::Points_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetauto_interfaces::Points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/PixelPosition[] points\n"
"================================================================================\n"
"MSG: jetauto_interfaces/PixelPosition\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::jetauto_interfaces::Points_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetauto_interfaces::Points_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Points_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetauto_interfaces::Points_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetauto_interfaces::Points_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::jetauto_interfaces::PixelPosition_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_POINTS_H
