// Generated by gencpp from file jetauto_interfaces/SetColorRGBA.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_SETCOLORRGBA_H
#define JETAUTO_INTERFACES_MESSAGE_SETCOLORRGBA_H

#include <ros/service_traits.h>


#include <jetauto_interfaces/SetColorRGBARequest.h>
#include <jetauto_interfaces/SetColorRGBAResponse.h>


namespace jetauto_interfaces
{

struct SetColorRGBA
{

typedef SetColorRGBARequest Request;
typedef SetColorRGBAResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetColorRGBA
} // namespace jetauto_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetauto_interfaces::SetColorRGBA > {
  static const char* value()
  {
    return "283c74850210286a04f67d9713622041";
  }

  static const char* value(const ::jetauto_interfaces::SetColorRGBA&) { return value(); }
};

template<>
struct DataType< ::jetauto_interfaces::SetColorRGBA > {
  static const char* value()
  {
    return "jetauto_interfaces/SetColorRGBA";
  }

  static const char* value(const ::jetauto_interfaces::SetColorRGBA&) { return value(); }
};


// service_traits::MD5Sum< ::jetauto_interfaces::SetColorRGBARequest> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetColorRGBA >
template<>
struct MD5Sum< ::jetauto_interfaces::SetColorRGBARequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetColorRGBA >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetColorRGBARequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetColorRGBARequest> should match
// service_traits::DataType< ::jetauto_interfaces::SetColorRGBA >
template<>
struct DataType< ::jetauto_interfaces::SetColorRGBARequest>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetColorRGBA >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetColorRGBARequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetauto_interfaces::SetColorRGBAResponse> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetColorRGBA >
template<>
struct MD5Sum< ::jetauto_interfaces::SetColorRGBAResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetColorRGBA >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetColorRGBAResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetColorRGBAResponse> should match
// service_traits::DataType< ::jetauto_interfaces::SetColorRGBA >
template<>
struct DataType< ::jetauto_interfaces::SetColorRGBAResponse>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetColorRGBA >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetColorRGBAResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_SETCOLORRGBA_H
