// Generated by gencpp from file jetauto_interfaces/SetColorDetectParamRequest.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_SETCOLORDETECTPARAMREQUEST_H
#define JETAUTO_INTERFACES_MESSAGE_SETCOLORDETECTPARAMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <jetauto_interfaces/ColorDetect.h>

namespace jetauto_interfaces
{
template <class ContainerAllocator>
struct SetColorDetectParamRequest_
{
  typedef SetColorDetectParamRequest_<ContainerAllocator> Type;

  SetColorDetectParamRequest_()
    : data()  {
    }
  SetColorDetectParamRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::jetauto_interfaces::ColorDetect_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::jetauto_interfaces::ColorDetect_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetColorDetectParamRequest_

typedef ::jetauto_interfaces::SetColorDetectParamRequest_<std::allocator<void> > SetColorDetectParamRequest;

typedef boost::shared_ptr< ::jetauto_interfaces::SetColorDetectParamRequest > SetColorDetectParamRequestPtr;
typedef boost::shared_ptr< ::jetauto_interfaces::SetColorDetectParamRequest const> SetColorDetectParamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetauto_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "255595acd127b3a1c9ee7a10b0920443";
  }

  static const char* value(const ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x255595acd127b3a1ULL;
  static const uint64_t static_value2 = 0xc9ee7a10b0920443ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/SetColorDetectParamRequest";
  }

  static const char* value(const ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/ColorDetect[] data\n"
"\n"
"================================================================================\n"
"MSG: jetauto_interfaces/ColorDetect\n"
"string color_name\n"
"string detect_type\n"
;
  }

  static const char* value(const ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetColorDetectParamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetauto_interfaces::SetColorDetectParamRequest_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::jetauto_interfaces::ColorDetect_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_SETCOLORDETECTPARAMREQUEST_H
