// Generated by gencpp from file jetauto_interfaces/SetInt64.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_SETINT64_H
#define JETAUTO_INTERFACES_MESSAGE_SETINT64_H

#include <ros/service_traits.h>


#include <jetauto_interfaces/SetInt64Request.h>
#include <jetauto_interfaces/SetInt64Response.h>


namespace jetauto_interfaces
{

struct SetInt64
{

typedef SetInt64Request Request;
typedef SetInt64Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt64
} // namespace jetauto_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetauto_interfaces::SetInt64 > {
  static const char* value()
  {
    return "b8a3204d8bafe68f75673256846654f5";
  }

  static const char* value(const ::jetauto_interfaces::SetInt64&) { return value(); }
};

template<>
struct DataType< ::jetauto_interfaces::SetInt64 > {
  static const char* value()
  {
    return "jetauto_interfaces/SetInt64";
  }

  static const char* value(const ::jetauto_interfaces::SetInt64&) { return value(); }
};


// service_traits::MD5Sum< ::jetauto_interfaces::SetInt64Request> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetInt64 >
template<>
struct MD5Sum< ::jetauto_interfaces::SetInt64Request>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetInt64 >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetInt64Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetInt64Request> should match
// service_traits::DataType< ::jetauto_interfaces::SetInt64 >
template<>
struct DataType< ::jetauto_interfaces::SetInt64Request>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetInt64 >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetInt64Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetauto_interfaces::SetInt64Response> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetInt64 >
template<>
struct MD5Sum< ::jetauto_interfaces::SetInt64Response>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetInt64 >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetInt64Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetInt64Response> should match
// service_traits::DataType< ::jetauto_interfaces::SetInt64 >
template<>
struct DataType< ::jetauto_interfaces::SetInt64Response>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetInt64 >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetInt64Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_SETINT64_H
