// Generated by gencpp from file jetauto_interfaces/SetLineROI.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_SETLINEROI_H
#define JETAUTO_INTERFACES_MESSAGE_SETLINEROI_H

#include <ros/service_traits.h>


#include <jetauto_interfaces/SetLineROIRequest.h>
#include <jetauto_interfaces/SetLineROIResponse.h>


namespace jetauto_interfaces
{

struct SetLineROI
{

typedef SetLineROIRequest Request;
typedef SetLineROIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLineROI
} // namespace jetauto_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetauto_interfaces::SetLineROI > {
  static const char* value()
  {
    return "35e53feacfaccfdf6f9964472d9f693d";
  }

  static const char* value(const ::jetauto_interfaces::SetLineROI&) { return value(); }
};

template<>
struct DataType< ::jetauto_interfaces::SetLineROI > {
  static const char* value()
  {
    return "jetauto_interfaces/SetLineROI";
  }

  static const char* value(const ::jetauto_interfaces::SetLineROI&) { return value(); }
};


// service_traits::MD5Sum< ::jetauto_interfaces::SetLineROIRequest> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetLineROI >
template<>
struct MD5Sum< ::jetauto_interfaces::SetLineROIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetLineROI >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetLineROIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetLineROIRequest> should match
// service_traits::DataType< ::jetauto_interfaces::SetLineROI >
template<>
struct DataType< ::jetauto_interfaces::SetLineROIRequest>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetLineROI >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetLineROIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetauto_interfaces::SetLineROIResponse> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetLineROI >
template<>
struct MD5Sum< ::jetauto_interfaces::SetLineROIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetLineROI >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetLineROIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetLineROIResponse> should match
// service_traits::DataType< ::jetauto_interfaces::SetLineROI >
template<>
struct DataType< ::jetauto_interfaces::SetLineROIResponse>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetLineROI >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetLineROIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_SETLINEROI_H
