// Generated by gencpp from file jetauto_interfaces/SetPose2DRequest.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_SETPOSE2DREQUEST_H
#define JETAUTO_INTERFACES_MESSAGE_SETPOSE2DREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <jetauto_interfaces/Pose2D.h>

namespace jetauto_interfaces
{
template <class ContainerAllocator>
struct SetPose2DRequest_
{
  typedef SetPose2DRequest_<ContainerAllocator> Type;

  SetPose2DRequest_()
    : data()  {
    }
  SetPose2DRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::jetauto_interfaces::Pose2D_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPose2DRequest_

typedef ::jetauto_interfaces::SetPose2DRequest_<std::allocator<void> > SetPose2DRequest;

typedef boost::shared_ptr< ::jetauto_interfaces::SetPose2DRequest > SetPose2DRequestPtr;
typedef boost::shared_ptr< ::jetauto_interfaces::SetPose2DRequest const> SetPose2DRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator1> & lhs, const ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetauto_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4a3a347bfab74ecc04cdc04f71890b6";
  }

  static const char* value(const ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4a3a347bfab74ecULL;
  static const uint64_t static_value2 = 0xc04cdc04f71890b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/SetPose2DRequest";
  }

  static const char* value(const ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetauto_interfaces/Pose2D data\n"
"\n"
"================================================================================\n"
"MSG: jetauto_interfaces/Pose2D\n"
"float64 x\n"
"float64 y\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPose2DRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetauto_interfaces::SetPose2DRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    s << std::endl;
    Printer< ::jetauto_interfaces::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_SETPOSE2DREQUEST_H
