// Generated by gencpp from file jetauto_interfaces/SetPose2D.msg
// DO NOT EDIT!


#ifndef JETAUTO_INTERFACES_MESSAGE_SETPOSE2D_H
#define JETAUTO_INTERFACES_MESSAGE_SETPOSE2D_H

#include <ros/service_traits.h>


#include <jetauto_interfaces/SetPose2DRequest.h>
#include <jetauto_interfaces/SetPose2DResponse.h>


namespace jetauto_interfaces
{

struct SetPose2D
{

typedef SetPose2DRequest Request;
typedef SetPose2DResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose2D
} // namespace jetauto_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetauto_interfaces::SetPose2D > {
  static const char* value()
  {
    return "a1bcdcb5bacc267b0cc863094ea73165";
  }

  static const char* value(const ::jetauto_interfaces::SetPose2D&) { return value(); }
};

template<>
struct DataType< ::jetauto_interfaces::SetPose2D > {
  static const char* value()
  {
    return "jetauto_interfaces/SetPose2D";
  }

  static const char* value(const ::jetauto_interfaces::SetPose2D&) { return value(); }
};


// service_traits::MD5Sum< ::jetauto_interfaces::SetPose2DRequest> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetPose2D >
template<>
struct MD5Sum< ::jetauto_interfaces::SetPose2DRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetPose2D >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetPose2DRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetPose2DRequest> should match
// service_traits::DataType< ::jetauto_interfaces::SetPose2D >
template<>
struct DataType< ::jetauto_interfaces::SetPose2DRequest>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetPose2D >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetPose2DRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetauto_interfaces::SetPose2DResponse> should match
// service_traits::MD5Sum< ::jetauto_interfaces::SetPose2D >
template<>
struct MD5Sum< ::jetauto_interfaces::SetPose2DResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetauto_interfaces::SetPose2D >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetPose2DResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetauto_interfaces::SetPose2DResponse> should match
// service_traits::DataType< ::jetauto_interfaces::SetPose2D >
template<>
struct DataType< ::jetauto_interfaces::SetPose2DResponse>
{
  static const char* value()
  {
    return DataType< ::jetauto_interfaces::SetPose2D >::value();
  }
  static const char* value(const ::jetauto_interfaces::SetPose2DResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETAUTO_INTERFACES_MESSAGE_SETPOSE2D_H
